### ISSUE TITLE
Position after rotation

### ISSUE THREAD

**Issue by N-Code-N** [uxmstudio/UXMVolumeOverlay#1]
Your lib is great!
Could you improve it by creating workaround of volume bar position after device rotation?
Now it keeps the initial position.

**Comment by pushchris** [comment]
Most definitely. May be a couple of days before I can get to it though, if you would like to contribute feel free to submit a pull request as well.

**Comment by pushchris** [comment]
Had a little extra time at the airport and took care of it. Let me know if you experience any other issues @N-Code-N
