### ISSUE TITLE
Always appears when seek in video ? 

### ISSUE THREAD

**Issue by fadylateef** [uxmstudio/UXMVolumeOverlay#6]
Hello, 
The overlay appears automatically always when video starts or when seek in video bar . 

Thanks again for such library

**Comment by pushchris** [comment]
How are you instantiating the video? Is the video playing inline or in fullscreen? Can you please provide a code example that shows this issue happening

**Comment by fadylateef** [comment]
I play videos using library mobileplayer-ios
[MobilePlayer-iOS](https://github.com/mobileplayer/mobileplayer-ios)

**Comment by pushchris** [comment]
That framework takes over the volume control in its own way so it is not compatible with UXMVolumeOverlay. Thanks
